"""make project icons nullable

Revision ID: e885746f73b8
Revises: 7d1da14c60ce
Create Date: 2025-05-07 01:58:04.148627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e885746f73b8'
down_revision: Union[str, None] = '7d1da14c60ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
